-- ============================================================================
-- ROLE DU FICHIER
-- Fichier SQL indicatif pour la version de schema v5.
--
-- IMPACT SUR LE PROJET
-- - le vrai travail se trouve dans `migration_v5.js`
-- - v5 nettoie les lignes `professeur_cours` liees a des cours archives
-- ============================================================================
-- migration_v5.sql
-- Nettoyage des affectations professeur_cours pointant vers des cours archives.
-- L'execution est geree par migration_v5.js.
